server:
  port: 9002

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: manta
      client-secret: secret
      access-token-uri: http://localhost:9001/oauth/token
      user-authorization-uri: http://localhost:9001/oauth/authorize
    resource:
      user-info-uri: http://localhost:9001/user/me
